### ISSUE TITLE
Can't reproduce the simple regret in the paper

### ISSUE THREAD

**Issue by ruipengZ** [deepmind/active_ops#1]
Hi! I really appreciate your work and code. But I run the code with the data provided, I can't reproduce the simple regret value in the paper. I got the regret for OPE around 8 but in the paper, it's much smaller and should be less than 1. 

Thank you!

**Comment by ksenia-konyushkova** [comment]
Hi! 

Thanks for your interest in our work.

The regret for OPE of around 8 sounds correct to me. In the paper, we normalise the regrets, see section 4.2 in https://arxiv.org/pdf/2106.10251.pdf. 
"To make the results comparable across domains, we first compute the gap between the best and the worst performing policy in each environment across all the policies. Then, we normalise the scores in each experiment by dividing them by this gap." 
I hope this helps!

Best regards,
Ksenia

**Comment by ruipengZ** [comment]
Thanks so much!
